# Generated by Django 5.0.7 on 2024-10-19 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AooHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="AOO開催タイトル")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
            ],
            options={
                "db_table": "AOO_HOLD",
            },
        ),
        migrations.CreateModel(
            name="AooRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(max_length=20, verbose_name="ユーザ名")),
                (
                    "user_participation",
                    models.BooleanField(blank=True, null=True, verbose_name="参加可否"),
                ),
                (
                    "user_position",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ポジション"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="パスワード"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "aoo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="aoo.aoohold"
                    ),
                ),
            ],
            options={
                "db_table": "AOO_REGISTER",
            },
        ),
    ]
