# Generated by Django 5.0.7 on 2024-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=20, verbose_name="user name"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="password")),
                ("role", models.CharField(max_length=20, verbose_name="role")),
            ],
            options={
                "db_table": "Accounts",
            },
        ),
    ]
