# Generated by Django 5.0.7 on 2024-10-21 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="id",
            new_name="user_id",
        ),
    ]
