# Generated by Django 5.0.7 on 2024-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aooregister",
            name="password",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="パスワード"
            ),
        ),
    ]
